# Generated by Django 3.1.2 on 2021-08-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.CharField(default='EmptyText', max_length=255),
        ),
    ]
